#!/usr/bin/env python3
"""Render the config.json reference table in docs/configuration.md from its schema.

Usage: scripts/config-reference.py [--check]
--check fails when the table differs from deploy/install/config.schema.json.
"""
import json
import pathlib
import sys

REPOSITORY = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPOSITORY / "deploy/install"))
import config_model  # noqa: E402

DOCUMENT = REPOSITORY / "docs/configuration.md"
BEGIN = "[//]: # (BEGIN config-reference: generated by scripts/config-reference.py from deploy/install/config.schema.json)"
END = "[//]: # (END config-reference)"
CHECKS = {"listen_host": "IPv4 or IPv6 address", "origin": "canonical origin; HTTP only on loopback unless allow_insecure_origin is true", "https_origin": "canonical HTTPS origin",
          "go_duration": "Go duration", "go_duration_min_1h": "Go duration, at least `1h`"}


def code(value):
    return "`" + json.dumps(value, ensure_ascii=False) + "`" if not isinstance(value, str) else f'`"{value}"`'


def kind(node):
    if "const" in node:
        return code(node["const"])
    if "enum" in node:
        return " \\| ".join(code(item) for item in node["enum"])
    types = node.get("type", [])
    types = [types] if isinstance(types, str) else list(types)
    names = []
    for name in types:
        if name == "array":
            names.append("array of " + kind(node.get("items", {})))
        elif name == "object" and isinstance(node.get("additionalProperties"), dict):
            names.append("object of " + kind(node["additionalProperties"]) + " values")
        else:
            names.append(name)
    text = " or ".join(names)
    if "minimum" in node and "maximum" in node:
        text += f' {node["minimum"]}–{node["maximum"]}'
    elif "minimum" in node:
        text += f' ≥ {node["minimum"]}'
    check = config_model.annotation(node, "check")
    if check:
        text += f" ({CHECKS[check]})"
    return text


def rows(node=None, prefix=""):
    """Leaves, plus nullable objects such as core.runtime_history, in schema order."""
    node = config_model.SCHEMA if node is None else node
    for name, child in node["properties"].items():
        if "properties" not in child or "default" in child:
            yield prefix + name, child
        if "properties" in child:
            yield from rows(child, prefix + name + ".")


def table():
    lines = ["| Key | Type | Default | Change | Restarts | Meaning |",
             "| --- | --- | --- | --- | --- | --- |"]
    for key, node in rows():
        annotation = lambda name, default=None: config_model.annotation(node, name, default)
        default = code(node["default"]) if "default" in node else "none"
        change = ("fixed" if not annotation("changeable", True)
                  else "`oac apply`" if annotation("setting", True) else "any time")
        restarts = ", ".join(annotation("restarts", [])) or "none"
        meaning = node.get("description", "")
        if annotation("sensitive"):
            meaning += " Sensitive."
        lines.append(f"| `{key}` | {kind(node)} | {default} | {change} | {restarts} | {meaning.strip()} |")
    return "\n".join(lines)


def install_flags():
    lines = ["| Flag | config.json field |", "| --- | --- |"]
    for key, node in rows():
        flag = config_model.annotation(node, "install_flag")
        if flag:
            flags = " or ".join(f"`{value}`" for value in flag.split(" or "))
            lines.append(f"| {flags} | `{key}` |")
    return "\n".join(lines)


def render_document(document, begin, end, body, check):
    text = document.read_text()
    before, found, rest = text.partition(begin + "\n")
    _, found_end, after = rest.partition(end)
    if not found or not found_end:
        sys.exit(f"{document} lacks generated reference markers")
    rendered = before + begin + "\n" + body + "\n" + end + after
    if check:
        if rendered != text:
            sys.exit(f"{document.relative_to(REPOSITORY)} is out of date; run scripts/config-reference.py")
        return
    document.write_text(rendered)


def main(argv):
    if argv not in ([], ["--check"]):
        sys.exit(__doc__.strip())
    check = bool(argv)
    render_document(DOCUMENT, BEGIN, END, table(), check)
    render_document(REPOSITORY / "docs/getting-started/install-options.md",
                    "[//]: # (BEGIN install-flags: generated by scripts/config-reference.py)",
                    "[//]: # (END install-flags)", install_flags(), check)


if __name__ == "__main__":
    main(sys.argv[1:])
